 
 
import { Metadata } from 'next';
import MainProduct from '../_component/mainProduct/MainProduct'


export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
};
export default   function page() {

 
  return  <>
   
 
 <MainProduct/>
  </>
}
